// advanced-fuzzing.js
// Modulo per l'integrazione di FFUF e Gobuster per fuzzing e discovery avanzati

class AdvancedFuzzing {
    constructor(executor, parser) {
        this.executor = executor;
        this.parser = parser;
    }

    async fuzzUrl(url, wordlistPath = "/usr/share/wordlists/dirbuster/directory-list-2.3-small.txt", extensions = "html,php,asp,aspx,jsp,txt,json,xml") {
        console.log(`Starting FFUF fuzzing on ${url} with wordlist ${wordlistPath}...`);
        try {
            // Ensure ffuf is installed. If not, executor should handle the error.
            const command = `ffuf -w ${wordlistPath}:FUZZ -u ${url}/FUZZ -e ${extensions} -mc all -sf -s -o /tmp/ffuf_results.json -ot json`;
            const rawResult = await this.executor.executeCommand("bash", ["-c", command]);
            
            // Read the output file generated by ffuf
            const fs = require("fs");
            if (fs.existsSync("/tmp/ffuf_results.json")) {
                const results = JSON.parse(fs.readFileSync("/tmp/ffuf_results.json", "utf8"));
                fs.unlinkSync("/tmp/ffuf_results.json"); // Clean up
                return results;
            } else {
                return { error: "FFUF output file not found or empty." };
            }
        } catch (error) {
            console.error(`Error during FFUF fuzzing: ${error.message}`);
            return { error: `FFUF command failed: ${error.message}` };
        }
    }

    async gobustDir(url, wordlistPath = "/usr/share/wordlists/dirbuster/directory-list-2.3-small.txt", extensions = "html,php,txt") {
        console.log(`Starting Gobuster directory enumeration on ${url} with wordlist ${wordlistPath}...`);
        try {
            // Ensure gobuster is installed.
            const command = `gobuster dir -u ${url} -w ${wordlistPath} -x ${extensions} -q`;
            const rawResult = await this.executor.executeCommand("bash", ["-c", command]);
            return this.parser.parse("gobuster", rawResult);
        } catch (error) {
            console.error(`Error during Gobuster directory enumeration: ${error.message}`);
            return { error: `Gobuster command failed: ${error.message}` };
        }
    }

    async gobustVhost(domain, wordlistPath = "/usr/share/wordlists/dirbuster/VHOSTS.txt") {
        console.log(`Starting Gobuster VHost enumeration on ${domain} with wordlist ${wordlistPath}...`);
        try {
            const command = `gobuster vhost -u ${domain} -w ${wordlistPath} -q`;
            const rawResult = await this.executor.executeCommand("bash", ["-c", command]);
            return this.parser.parse("gobuster", rawResult);
        } catch (error) {
            console.error(`Error during Gobuster VHost enumeration: ${error.message}`);
            return { error: `Gobuster VHost command failed: ${error.message}` };
        }
    }
}

module.exports = AdvancedFuzzing;
